### ISSUE TITLE
Acceptable screen size variations are not matching.

### ISSUE THREAD

**Issue by sent0007** [sent0007/sections#1]
I am unable to make all the screen size variations match the acceptable limits simultaneously.
As it stands, all of the sizes work, except for 960 px screen size.
When I adjust to make the 960px screen size acceptable, 320px, 400px and 608 px screen sizes are then not accepted.

I believe that it is a margin or padding issue but i'm not sure. I've tried numerous different combinations to make the same spacing differences, but none of them seem to work. Also embedded is the quiz from last week.

Thank you for reading. @thomasjbradley

https://github.com/sent0007/sections/blob/gh-pages/css/main.css

https://github.com/sent0007/sections/blob/gh-pages/index.html

![Screen Shot 2019-10-24 at 1 05 49 PM](https://user-images.githubusercontent.com/55108791/67509205-7a42c400-f660-11e9-8763-cc60f74aad89.png)

![Screen Shot 2019-10-24 at 1 03 33 PM](https://user-images.githubusercontent.com/55108791/67509246-934b7500-f660-11e9-8db4-d09b2288972f.png)

![Screen Shot 2019-10-17 at 11 05 37 PM](https://user-images.githubusercontent.com/55108791/67509923-099ca700-f662-11e9-81ba-a127aac67cba.png)

**Comment by thomasjbradley** [comment]
*Re: Display Dominator—*

Thanks, I’ve added your grade.

**Comment by thomasjbradley** [comment]
*Re: sections—*

Let’s adjust some margins & paddings:

1. Remove the top margin from the `p` tag
2. Set only the bottom margin of the `p` & `h1` to `1.5rem`
3. The `section` should have padding on the top & bottom of `2em`
4. The `div` tags should have equal padding on all for sides of `1em`

And `vertical-align` middle needs to move from `section` onto `div`

**Comment by sent0007** [comment]
Aha, thanks again for the help!
